name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request_target:
    branches: [develop]
  schedule:
    - cron: '0 0 * * *'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'echo "$FXL_CI" > resources/credentials.json'
        shell: bash
        env:
          FXL_CI: ${{secrets.FXL_CI}}
      - name: unit-tests
        uses: docker://zeroonetechnology/fxl:latest
        with:
          entrypoint: scripts/coverage
      - uses: codecov/codecov-action@v1
        with:
         file: target/coverage/codecov.json
         fail_ci_if_error: true
  lint-ancient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint-ancient
        uses: docker://zeroonetechnology/fxl:latest
        with:
          entrypoint: scripts/lint-ancient
